name: CI/CD Backend

on:
  push:
    branches:
      - main
      - test
      - dev
  pull_request:
    branches:
      - main
      - test
      - dev
    types: [opened, synchronize] 

jobs:
  build-test:
    name: Build and Test (Matrix Strategy)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [build, test] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Execute Maven command
      run: |
        if [ "${{ matrix.task }}" == "build" ]; then
          mvn clean package -DskipTests;
        elif [ "${{ matrix.task }}" == "test" ]; then
          mvn test;
        fi

  linter:
    name: Code Linter
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' || github.ref_name == 'test' 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Install Maven Checkstyle Plugin
      run: mvn checkstyle:checkstyle

    - name: Run Checkstyle Linter
      run: |
        mvn checkstyle:check
        echo "Linter analysis completed."
